version: '3.2'

services:
  postgres:
    container_name: frontend_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frontend_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data/

