version: "3.9"

services:

  # ----------------------------------------------------------------------------
  # Ethereum private devenet:
  # ----------------------------------------------------------------------------

  ethereum_node1:
    command: --datadir /root/private_network/node1 --networkid 1234 --port 30304
      --nodiscover --http --http.addr 0.0.0.0 --http.port 8545
      --ipcpath /root/private_network/node1/geth.ipc --mine --miner.threads 1
      --miner.gasprice "10000" --miner.etherbase 0xafb72ccaeb7e22c8a7640f605824b0898424b3da
      --verbosity 5 --allow-insecure-unlock --fakepow --http.api eth,web3,personal,admin
      --unlock 0xafb72ccaeb7e22c8a7640f605824b0898424b3da
      --password /root/private_network/password
      --http.vhosts=*
    hostname: ethereum
    image: ethereum/client-go:stable
    ports:
    - 30304:30304
    - 8545:8545
    volumes:
    - ./geth_nodes/private_network:/root/private_network

  ethereum_node2:
    command: --datadir /root/private_network/node2 --networkid 1234 --port 30305
      --nodiscover --http --http.addr 0.0.0.0 --http.port 8546
      --ipcpath /root/private_network/node2/geth.ipc --mine --miner.threads 1
      --miner.gasprice "10000" --miner.etherbase 0x77b648683cde1d69544ed6f4f7204e8d51c324db
      --verbosity 5 --allow-insecure-unlock --fakepow --http.api eth,web3,personal,admin
      --unlock 0x77b648683cde1d69544ed6f4f7204e8d51c324db
      --password /root/private_network/password
      --http.vhosts=*
    hostname: ethereum
    image: ethereum/client-go:stable
    ports:
    - 30305:30305
    - 8546:8546
    volumes:
    - ./geth_nodes/private_network:/root/private_network

  # ----------------------------------------------------------------------------
  # Wargame Tooling Client
  # ----------------------------------------------------------------------------

  eth_client:
    build: ./eth_client/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 43487:43487
    volumes:
      - ./eth_client/:/app/
    environment:
      - ETH_API_KEY
      - ETH_CHAIN_ID
      - ETH_RPC_HOST
      - ETH_USER_ADDRESS
      - ETH_USER_PK

  # ----------------------------------------------------------------------------
  # Livebook Frontend
  # ----------------------------------------------------------------------------
  
  livebook:
    image: livebook/livebook
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./livebooks/:/home/livebook/
    environment:
      - LIVEBOOK_HOME=/home/livebook/
      - LIVEBOOK_TOKEN_ENABLED=false
      - LIVEBOOK_DEFAULT_RUNTIME=attached:eth_client@eth_client:mycookie
