version: "3.9"
services:

  eth_client:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 43487:43487
    volumes:
      - .:/app/

  livebook:
    image: livebook/livebook
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./livebooks/:/home/livebook/
    environment:
      - LIVEBOOK_HOME=/home/livebook/
      - LIVEBOOK_TOKEN_ENABLED=false
      - LIVEBOOK_DEFAULT_RUNTIME=attached:eth_client@eth_client:mycookie
