version: "3.9"
services:

  eth_client:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: iex --name eth_client@eth_client --cookie mycookie -S mix
    ports:
      - 43487:43487

  livebook:
    image: livebook/livebook
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - .:/home/livebook/
    environment:
      - LIVEBOOK_HOME=/home/livebook/livebooks
      - LIVEBOOK_TOKEN_ENABLED=false
      - LIVEBOOK_DEFAULT_RUNTIME=attached:eth_client@eth_client:mycookie
